http:
  routers:
    redirect-to-https:
      rule: "HostRegexp(`{any:.+}`)"
      entryPoints:
        - web
      middlewares:
        - redirectscheme
      service: noop
  middlewares:
    redirectscheme:
      redirectScheme:
        scheme: https
  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1"
